# Generated by Django 2.2 on 2019-07-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empid', models.CharField(blank=True, default=True, max_length=30)),
                ('Empname', models.CharField(blank=True, default=True, max_length=30)),
                ('Empsal', models.IntegerField(blank=True, default=True)),
                ('Empexp', models.IntegerField(blank=True, default=True)),
                ('Empadd', models.CharField(blank=True, default=True, max_length=30)),
            ],
        ),
    ]
